### ISSUE TITLE
mockable indexedDB

### ISSUE THREAD

**Issue by bsr203** [dumbmatter/backboard#1]
Hi,

Is it possible to accept `indexedDB` through `Backboard` constructor than using the global instance? My usecase is to pass [fakeIndexedDB](https://github.com/dumbmatter/fakeIndexedDB) instance for unittesting as I use `jsdom` which has no support for `indexedDB`.

thanks for your work on this library and making it available.

cheers,
bsr.

**Comment by bsr203** [comment]
well, I wasn't thinking about other globals like `IDBKeyRange` and may better to add all these to window/global during my test setup. Do you think that is better?

**Comment by dumbmatter** [comment]
Yeah, that's what I do here https://github.com/dumbmatter/backboard/blob/master/test/root.js#L30-L36 because there are a lot of globals in IndexedDB.

**Comment by bsr203** [comment]
thank you for the quick response.
