### ISSUE TITLE
console.log

### ISSUE THREAD

**Issue by bsr203** [dumbmatter/backboard#2]
hi,

there are many `console.log` statements in 

https://github.com/dumbmatter/backboard/blob/master/lib/DB.js

do you think it better to remove them. I see them in my console like

`DB VERSIONCHANGE`

thanks.
bsr.

**Comment by dumbmatter** [comment]
I released v1.0.5 to fix this problem, thanks for the bug report!

**Comment by bsr203** [comment]
thanks.
